#!/usr/bin/env bash

NAV_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

config="$NAV_PATH/.nav.config"
if [ ! -f "$config" ]; then
    touch "$config"
fi

help_pin="Usage: nav pin [location] [alias]"
help_to="Usage: nav to [alias]"
help_rm="Usage: nav rm [alias]"

resolve_alias () {
    local location

    while read line; do
        local alias=$(echo "$line" | cut -d "=" -f 1)

        if [ "$1" == "$alias" ]; then
            location=$(echo "$line" | cut -d "=" -f 2)
            break;
        fi
    done < "$config"

    if [ ! -z "$location" ]; then
        echo "$location"
    fi
}

alias_location () {
    local location="$1"
    local alias="$2"

    if [[ -z "$location" || -z "$alias" ]]; then
        echo "$help_pin"
        return 0
    fi

    if [ ${location:0:1} = "." ]; then
        location="$(pwd)${location:1}"
    elif [ ! ${location:0:1} = "/" ]; then
        location="$(pwd)/$location"
    elif [ ${location:0:1} = "~" ]; then
        location="$("$location")"
    fi

    if [ ! -d "$location" ]; then
        echo "$location is not a directory"
        return 0
    fi

    local existing_alias=$(resolve_alias "$alias")
    if [ ! -z "$existing_alias" ]; then
        echo "Overwriting existing value for $alias"
        delete_alias "$alias"
    fi

    echo "$alias=$location" >> "$config"
}

goto_location () {
    local alias="$1"

    if [ -z "$alias" ]; then
        echo "$help_to"
        return 0
    fi

    local location=$(resolve_alias "$alias")

    if [ -z "$location" ]; then
        echo "No alias found matching $alias"
        return 0
    fi

    cd "$location"
}

delete_alias () {
    local alias="$1"

    if [ -z "$alias" ]; then
        echo "$help_rm"
        return 0;
    fi

    sed -i '' "/^$alias/d" "$config"
}

list_aliases () {
    cat "$config"
}

get_installation_location () {
    echo "$NAV_PATH"
}

get_usage_instructions () {
    echo "Available actions:"
    echo "- pin ($help_pin)"
    echo "- to ($help_to)"
    echo "- rm ($help_rm)"
    echo "- list"
    echo "- which"
}

nav () {
    action="$1"

    case "$action" in
        (pin) alias_location "$2" "$3";;
        (to) goto_location "$2";;
        (list) list_aliases;;
        (rm) delete_alias "$2";;
        (help) get_usage_instructions;;
        (which) get_installation_location;;
        (*) nav help ;;
    esac
}

export nav
