on: [push, pull_request]

name: Test

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: results=$(./nav.test.sh)
    - run: if [ ! ${results:0:4} == Pass ]; then return 0; fi
